serviceId: hwexpress
title: Hello World express REST API
eureka:
  ssl: true
  hostname: localhost
  ipAddress: 127.0.0.1
  port: 10020
  servicePath: '/eureka/apps/'

description: Hello World REST API Service implemented in Express and Node.js
baseUrl: https://localhost:10020/hwexpress
homePageRelativeUrl: https://localhost:10020/
statusPageRelativeUrl: https://localhost:10020/info
healthCheckRelativeUrl: https://localhost:10020/status
discoveryServiceUrls:
  - https://localhost:10011/eureka
routes:
  - gatewayUrl: api/v1
    serviceRelativeUrl: /api/v1
apiInfo:
  - apiId: org.zowe.hwexpress
    gatewayUrl: "api/v1"
    swaggerUrl: https://localhost:10020/swagger.json
catalogUiTile:
  id: cademoapps
  title: Sample API Mediation Layer Applications
  description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
  version: 1.0.0
instance:
  app: hwexpress
  vipAddress: hwexpress
  instanceId: localhost:hwexpress:10020
  homePageUrl: https://localhost:10020/
  hostName: 'localhost'
  ipAddr: '127.0.0.1'
  secureVipAddress: hwexpress
  port:
    $: 10020
    '@enabled': false
  securePort:
    $: 10020
    '@enabled': "true"

  dataCenterInfo:
    '@class': com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo
    name: MyOwn
  metadata:
    apiml.apiInfo.0.apiId: org.zowe.hwexpress
    apiml.apiInfo.0.gatewayUrl: "api/v1"
    apiml.apiInfo.0.swaggerUrl: https://localhost:10020/swagger.json
    mfaas.discovery.catalogUiTile.id: 'samplenodeservice'
    mfaas.discovery.catalogUiTile.title: 'Zowe Sample Node Service'
    mfaas.discovery.catalogUiTile.description: 'Sample service running '
    mfaas.discovery.catalogUiTile.version: '1.0.0'
    mfaas.discovery.service.title: 'Zowe Sample Node Service'
    mfaas.discovery.service.description: 'The Proxy Server is an HTTP HTTPS, and Websocket server built upon NodeJS and ExpressJS.'
    routed-services.0.gateway-url: "api/v1"
    routed-services.0.service-url: "/api/v1"

ssl:
  certificate: ssl/localhost.keystore.cer
  keystore: ssl/localhost.keystore.key
  caFile: ssl/localhost.pem
  keyPassword: password
